settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: LAX18.jpeg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: server1.nicholaspease.com
    name: Server1 Homepage
    url: 'https://server1.nicholaspease.com/'
    method: GET
    expectStatus: 200

  - id: plex.nicholaspease.com
    name: Plex
    url: 'https://plex.nicholaspease.com/'
    method: GET
    expectStatus: 200

  - id: radarr.nicholaspease.com
    name: Radarr
    url: 'https://radarr.nicholaspease.com/'
    method: GET
    expectStatus: 200

  - id: sonarr.nicholaspease.com
    name: Sonarr
    url: 'https://sonarr.nicholaspease.com/'
    method: GET
    expectStatus: 200

  - id: bittorrent.nicholaspease.com
    name: qBittorrent
    url: 'https://bittorrent.nicholaspease.com/'
    method: GET
    expectStatus: 200

  - id: prowlarr.nicholaspease.com
    name: Prowlarr
    url: 'https://prowlarr.nicholaspease.com/'
    method: GET
    expectStatus: 403

  - id: bazarr.nicholaspease.com
    name: Bazarr
    url: 'https://bazarr.nicholaspease.com/'
    method: GET
    expectStatus: 200

  - id: petio.nicholaspease.com
    name: Petio
    url: 'https://petio.nicholaspease.com/'
    method: GET
    expectStatus: 200

  - id: tautulli.nicholaspease.com
    name: Tautulli
    url: 'https://tautulli.nicholaspease.com/'
    method: GET
    expectStatus: 200

  - id: gitea.nicholaspease.com
    name: Gitea
    url: 'https://gitea.nicholaspease.com/'
    method: GET
    expectStatus: 200
  
  - id: coder.nicholaspease.com
    name: Coder
    url: 'https://coder.nicholaspease.com/'
    method: GET
    expectStatus: 200